### ISSUE TITLE
Breaking changes to protobuf

### ISSUE THREAD

**Issue by tbrx** [john-bradshaw/synthesis-dags#1]
Hi, I just installed this on a new machine and found one issue regarding the `conda_dogae_gpu.yml` environment setup. Namely, it seems like Google recently introduced backwards-incompatible changes to protobuf:

https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

I'm not exactly clear on what changed, but the suggested option of downgrading to `protobuf==3.20` (via pip) worked for me. There may be a better option (… regenerating some _pb2 files?), but otherwise would suggest updating the environment to pin version on protobuf.

**Comment by john-bradshaw** [comment]
Thanks for this!

I just checked what version of `protobuf` I was likely using at the time (by looking at the Docker images), and it seems 3.14.0, but otherwise I'll follow your suggestion!
